Update2Budget.cpp
OsamaAshraf01/Ra7al pull request #16
Opened 2024-04-06 13:38 UTC by AhmedHamdyKotp

2024-04-06 15:06 UTC, OsamaAshraf01 requested changes
Nice Work !! Just make the little changes I has mentioned :)

2024-04-06 15:06 UTC, OsamaAshraf01 commented on src/Budget.cpp
> +#include "Budget.h"
Budget.h is in 'include' folder. use "../include/Budget.h" instead.

2024-04-06 15:06 UTC, OsamaAshraf01 commented on src/Budget.cpp
> +Budget::Budget() : total_budget(0.0) {}
Provide another constructor with parameters.

2024-04-06 15:06 UTC, OsamaAshraf01 commented on src/Budget.cpp
> +    categories[category_name] = 0.0;
Make sure that this category doesn't exist already. In this case, if the category already exists, this existent value will be removed and returned to zero.

2024-04-06 15:06 UTC, OsamaAshraf01 commented on src/Budget.cpp
> +    return bal != categories.end() ? bal->second : 0.0;
if a category is not found, don't return zero as it's misleading (some existent categories may have 0 balance). Return any value that demonstrate that this category is not found (for example, -1);

2024-04-06 15:06 UTC, OsamaAshraf01 commented on src/Budget.cpp
> +    if (categories[category_name] >= amount) {
Make sure that the category is found.

2024-04-06 15:06 UTC, OsamaAshraf01 commented on src/Budget.cpp
> +    categories[category_name] += amount;
same here

2024-04-06 15:06 UTC, OsamaAshraf01 commented on src/Budget.cpp
> +    double total = 0.0;
Isn't this the total remaining?

2024-04-06 15:06 UTC, OsamaAshraf01 commented on src/Budget.cpp
> +        categories[category_name] -= amount; total_budget -= amount;
Don't decrease total_budget as this make it equal to total_ramining

2024-04-06 16:02 UTC, AhmedHamdyKotp commented
> Nice Work !! Just make the little changes I has mentioned :)

All done

2024-04-06 20:12 UTC, OsamaAshraf01 requested changes
Make isFound() method and use it instead of repeating for a loop.

2024-04-06 20:12 UTC, OsamaAshraf01 commented on src/Budget.cpp
> +    }
Make a method that checks if a category is already found or not.

2024-04-06 20:12 UTC, OsamaAshraf01 commented on src/Budget.cpp
> +        }
Instead of repeating this loop, make the functions I have mentioned.
```C++
if(!isFound()){
     // Your implementation goes here
}
```

2024-04-09 20:17 UTC, OsamaAshraf01 commented
Please review my last comment to merge this pull request.

2024-04-12 15:04 UTC, OsamaAshraf01 approved these changes
Great Job my friend :)

2024-04-12 15:05 UTC, merged