Create Destination.cpp
OsamaAshraf01/Ra7al pull request #57
Opened 2024-04-24 12:15 UTC by AhmedHamdyKotp

خالد هيظبط الكلاسين بتوعه وقشطا على كده

2024-04-26 15:03 UTC, OsamaAshraf01 requested changes

2024-04-26 15:03 UTC, OsamaAshraf01 commented on src/Destination.cpp
> +    }
Why are you doing this step?

2024-04-26 15:03 UTC, OsamaAshraf01 commented on src/Destination.cpp
> +    }
Same here

2024-04-26 15:03 UTC, OsamaAshraf01 commented on src/Destination.cpp
> +    }
and here

2024-04-27 06:15 UTC, AhmedHamdyKotp commented on src/Destination.cpp
> +    }
To give him the ability to assign his activities for this distension

2024-04-27 10:50 UTC, OsamaAshraf01 commented on src/Destination.cpp
> +    }
```C++
this->activities = activities;
```
Is enough

2024-04-27 16:11 UTC, AhmedHamdyKotp commented on src/Destination.cpp
> +    }
بحب اكتب يسطا  : )

2024-04-28 04:32 UTC, OsamaAshraf01 commented on src/Destination.cpp
> +    }
The problem is although you wrote 15 redundant lines, those lines are doing nothing 😄.
you are getting the name of an activity and setting it in the same activity.
```C++
string name = activity.getName();
activity.setName(name);
```

2024-04-28 12:57 UTC, merged